"""phase7 orcid_publications and advisor_fit

Revision ID: 0560059db985
Revises: f8cb8d18794e
Create Date: 2026-05-14 20:28:17.447681

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0560059db985'
down_revision: Union[str, None] = 'f8cb8d18794e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcid_publications',
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('put_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('journal', sa.String(length=500), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisor_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advisor_id', 'put_code', name='uq_orcid_publications_advisor_put_code')
    )
    op.create_index(op.f('ix_orcid_publications_advisor_id'), 'orcid_publications', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_orcid_publications_doi'), 'orcid_publications', ['doi'], unique=False)
    op.add_column('submissions', sa.Column('advisor_fit_score', sa.Float(), nullable=True))
    op.add_column(
        'submissions',
        sa.Column(
            'advisor_fit_alert',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.create_index(op.f('ix_submissions_advisor_fit_alert'), 'submissions', ['advisor_fit_alert'], unique=False)
    # Drop the server_default once the column is populated — the application
    # layer is the source of truth from here on.
    op.alter_column('submissions', 'advisor_fit_alert', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_advisor_fit_alert'), table_name='submissions')
    op.drop_column('submissions', 'advisor_fit_alert')
    op.drop_column('submissions', 'advisor_fit_score')
    op.drop_index(op.f('ix_orcid_publications_doi'), table_name='orcid_publications')
    op.drop_index(op.f('ix_orcid_publications_advisor_id'), table_name='orcid_publications')
    op.drop_table('orcid_publications')
    # ### end Alembic commands ###
