"""phase10 fine_tuning_jobs and system_settings

Revision ID: 2298185806fd
Revises: 0560059db985
Create Date: 2026-05-15 07:26:34.307337

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2298185806fd'
down_revision: Union[str, None] = '0560059db985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fine_tuning_jobs',
    sa.Column('status', sa.Enum('dataset_ready', 'uploading', 'queued', 'running', 'succeeded', 'failed', 'cancelled', name='fine_tuning_status'), nullable=False),
    sa.Column('dataset_path', sa.String(length=512), nullable=False),
    sa.Column('examples_count', sa.Integer(), nullable=False),
    sa.Column('base_model', sa.String(length=100), nullable=False),
    sa.Column('openai_file_id', sa.String(length=200), nullable=True),
    sa.Column('openai_job_id', sa.String(length=200), nullable=True),
    sa.Column('fine_tuned_model', sa.String(length=200), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openai_job_id')
    )
    op.create_index(op.f('ix_fine_tuning_jobs_status'), 'fine_tuning_jobs', ['status'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_fine_tuning_jobs_status'), table_name='fine_tuning_jobs')
    op.drop_table('fine_tuning_jobs')
    # ### end Alembic commands ###
