"""phase5 document_chunks and plagiarism_matches

Revision ID: 273dd3290cc0
Revises: 7c68e36bc49b
Create Date: 2026-05-14 14:31:39.506044

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector  # noqa: F401  - referenced in column types below


# revision identifiers, used by Alembic.
revision: str = '273dd3290cc0'
down_revision: Union[str, None] = '7c68e36bc49b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['submission_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_version_id'), 'document_chunks', ['version_id'], unique=False)
    op.create_table('plagiarism_matches',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('matched_version_id', sa.UUID(), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=False),
    sa.Column('matched_chunk_id', sa.UUID(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('intra', 'copyleaks', name='plagiarism_source'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'dismissed', name='plagiarism_status'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_version_id'], ['submission_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['submission_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plagiarism_matches_matched_version_id'), 'plagiarism_matches', ['matched_version_id'], unique=False)
    op.create_index(op.f('ix_plagiarism_matches_status'), 'plagiarism_matches', ['status'], unique=False)
    op.create_index(op.f('ix_plagiarism_matches_version_id'), 'plagiarism_matches', ['version_id'], unique=False)
    # ### end Alembic commands ###

    # HNSW index for cosine similarity search on document_chunks.embedding.
    # HNSW works on empty tables (unlike ivfflat) and gives sub-linear search.
    op.execute(
        "CREATE INDEX ix_document_chunks_embedding_hnsw "
        "ON document_chunks USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_document_chunks_embedding_hnsw")
    op.drop_index(op.f('ix_plagiarism_matches_version_id'), table_name='plagiarism_matches')
    op.drop_index(op.f('ix_plagiarism_matches_status'), table_name='plagiarism_matches')
    op.drop_index(op.f('ix_plagiarism_matches_matched_version_id'), table_name='plagiarism_matches')
    op.drop_table('plagiarism_matches')
    op.drop_index(op.f('ix_document_chunks_version_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
