"""phase3 submissions and versions

Revision ID: 2f67c147d36f
Revises: 80bbcdae218f
Create Date: 2026-05-14 11:36:28.786613

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f67c147d36f'
down_revision: Union[str, None] = '80bbcdae218f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('advisor_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('chapter', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'observed', 'approved', 'rejected', name='submission_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['academic_programs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['template_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_advisor_id'), 'submissions', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_submissions_program_id'), 'submissions', ['program_id'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    op.create_index(op.f('ix_submissions_template_id'), 'submissions', ['template_id'], unique=False)
    op.create_table('submission_versions',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('parsing_status', sa.Enum('pending', 'processing', 'parsed', 'failed', 'ai_queued', 'ai_processing', 'ai_completed', name='version_parsing_status'), nullable=False),
    sa.Column('parsing_error', sa.String(length=2000), nullable=True),
    sa.Column('structure_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'version_number', name='uq_submission_versions_submission_version')
    )
    op.create_index(op.f('ix_submission_versions_file_sha256'), 'submission_versions', ['file_sha256'], unique=False)
    op.create_index(op.f('ix_submission_versions_parsing_status'), 'submission_versions', ['parsing_status'], unique=False)
    op.create_index(op.f('ix_submission_versions_submission_id'), 'submission_versions', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_versions_submission_id'), table_name='submission_versions')
    op.drop_index(op.f('ix_submission_versions_parsing_status'), table_name='submission_versions')
    op.drop_index(op.f('ix_submission_versions_file_sha256'), table_name='submission_versions')
    op.drop_table('submission_versions')
    op.drop_index(op.f('ix_submissions_template_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_program_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_advisor_id'), table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###
