"""phase4 ai_evaluations and ai_findings

Revision ID: 7c68e36bc49b
Revises: 2f67c147d36f
Create Date: 2026-05-14 11:52:38.412262

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c68e36bc49b'
down_revision: Union[str, None] = '2f67c147d36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_evaluations',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('backend', sa.String(length=20), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('structure_score', sa.Float(), nullable=False),
    sa.Column('content_score', sa.Float(), nullable=False),
    sa.Column('form_score', sa.Float(), nullable=False),
    sa.Column('originality_score', sa.Float(), nullable=False),
    sa.Column('total_percentage', sa.Float(), nullable=False),
    sa.Column('decimal_grade', sa.Float(), nullable=False),
    sa.Column('executive_summary', sa.String(length=4000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['submission_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_evaluations_version_id'), 'ai_evaluations', ['version_id'], unique=True)
    op.create_table('ai_findings',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('page_approx', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('missing_section', 'structural_error', 'content_error', 'form_error', 'coherence_issue', 'suggestion', name='finding_type'), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'major', 'minor', 'suggestion', name='finding_severity'), nullable=False),
    sa.Column('severity_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('instruction', sa.String(length=4000), nullable=False),
    sa.Column('example', sa.String(length=4000), nullable=False),
    sa.Column('recommendation', sa.String(length=2000), nullable=False),
    sa.Column('human_action', sa.Enum('accepted', 'modified', 'rejected', name='finding_human_action'), nullable=True),
    sa.Column('human_comment', sa.String(length=4000), nullable=True),
    sa.Column('human_severity_override', sa.Enum('critical', 'major', 'minor', 'suggestion', name='finding_severity_override'), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['ai_evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_findings_evaluation_id'), 'ai_findings', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_ai_findings_human_action'), 'ai_findings', ['human_action'], unique=False)
    op.create_index(op.f('ix_ai_findings_severity'), 'ai_findings', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_findings_severity'), table_name='ai_findings')
    op.drop_index(op.f('ix_ai_findings_human_action'), table_name='ai_findings')
    op.drop_index(op.f('ix_ai_findings_evaluation_id'), table_name='ai_findings')
    op.drop_table('ai_findings')
    op.drop_index(op.f('ix_ai_evaluations_version_id'), table_name='ai_evaluations')
    op.drop_table('ai_evaluations')
    # ### end Alembic commands ###
