"""phase2 template_documents

Revision ID: 80bbcdae218f
Revises: 93c7cf1b6cdf
Create Date: 2026-05-14 11:02:43.842746

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80bbcdae218f'
down_revision: Union[str, None] = '93c7cf1b6cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_documents',
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('parsing_status', sa.Enum('pending', 'processing', 'parsed', 'failed', name='template_parsing_status'), nullable=False),
    sa.Column('parsing_error', sa.String(length=2000), nullable=True),
    sa.Column('structure_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rubric_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['program_id'], ['academic_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'version', name='uq_template_documents_program_version')
    )
    op.create_index(op.f('ix_template_documents_file_sha256'), 'template_documents', ['file_sha256'], unique=False)
    op.create_index(op.f('ix_template_documents_is_active'), 'template_documents', ['is_active'], unique=False)
    op.create_index(op.f('ix_template_documents_program_id'), 'template_documents', ['program_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_documents_program_id'), table_name='template_documents')
    op.drop_index(op.f('ix_template_documents_is_active'), table_name='template_documents')
    op.drop_index(op.f('ix_template_documents_file_sha256'), table_name='template_documents')
    op.drop_table('template_documents')
    # ### end Alembic commands ###
