"""phase6 citations

Revision ID: f8cb8d18794e
Revises: 273dd3290cc0
Create Date: 2026-05-14 15:37:17.907313

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8cb8d18794e'
down_revision: Union[str, None] = '273dd3290cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citations',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('authors', sa.String(length=1000), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('journal', sa.String(length=500), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('crossref_status', sa.Enum('pending', 'verified', 'partial', 'not_found', 'hallucinated', name='citation_status'), nullable=False),
    sa.Column('crossref_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('crossref_message', sa.String(length=1000), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['submission_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_crossref_status'), 'citations', ['crossref_status'], unique=False)
    op.create_index(op.f('ix_citations_doi'), 'citations', ['doi'], unique=False)
    op.create_index(op.f('ix_citations_version_id'), 'citations', ['version_id'], unique=False)
    # ### end Alembic commands ###

    # Re-create the HNSW index on document_chunks.embedding. Autogenerate dropped
    # it because pgvector's operator class isn't tracked by SQLAlchemy metadata;
    # in production this is recreated idempotently.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_document_chunks_embedding_hnsw "
        "ON document_chunks USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citations_version_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_doi'), table_name='citations')
    op.drop_index(op.f('ix_citations_crossref_status'), table_name='citations')
    op.drop_table('citations')
    # ### end Alembic commands ###
